### ISSUE TITLE
Does this wrap all Win API or just the ones listed?

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [131/node-winapi#1]
Does this wrap all Win API or just the ones listed?

**Comment by 131** [comment]
for now, only API i've encountered/needed so far. Feel free to ask/ pr new ones

**Comment by MichaelLeeHobbs** [comment]
Basically was looking to do Desktop Automation. Currently using AutoIT but would love to use nodejs. Will take a look at the code latter. Not sure how much c/c++ my jr devs know.
