### ISSUE TITLE
Could you add CreateProcessAsUserA, CreateProcessWithLogonW and also LogonUserA?

### ISSUE THREAD

**Issue by sebastiaorealino** [131/node-winapi#4]
I can resolve some problem with robotjs, like:
https://github.com/octalmage/robotjs/issues/669
https://github.com/octalmage/robotjs/issues/645#issuecomment-872617642

It would be very useful to solve these problems. 

Can anyone help me with that?

Thanks!

**Comment by 131** [comment]
May i suggest you to give [131/dispatcher](https://github.com/131/dispatcher) a try
